/**
 * THE OPERATOR SETTING REGISTRY — the single declarative list of what an operator may change.
 *
 * WHAT IS DELIBERATELY *NOT* HERE, AND WHY THAT IS THE POINT
 *
 * `loadBoxConfig()` parses 131 fields. This registry has a deliberately small fraction of them. The
 * goal of this subsystem is to REDUCE operator complexity, not to move `.env` into a web form, so a
 * setting earns a place here only if an operator has a concrete reason to change it during a trading
 * day. Everything below stays deployment configuration and is read-only in the UI:
 *
 *   deployment capability  BOX_EXECUTION_MODE, BOX_LIVE_TRADING_ENABLED,
 *                          ZERODHA_/DHAN_LIVE_TRADING_ENABLED, BOX_SHADOW_MODE_ENABLED,
 *                          BOX_EXECUTION_COORDINATOR_ENABLED — a runtime control must never be able
 *                          to turn a paper deployment into a live-capable one
 *   reservation machinery  lock TTLs, renew intervals, clock-skew grace, uncertain-hold windows
 *   transport and pacing   broker min intervals, entry submit concurrency, every live timeout
 *   queue internals        chase ticks, queue model, liquidity haircut, tick size
 *   loops and metrics      monitor/persist/publish intervals, metric windows, timing persistence
 *   reconciliation         reconcile intervals, feed reconnect warm-up
 *   infrastructure         PORT, DATABASE_URL, pool sizing, Mongo export, proxies, broker API roots
 *
 * See `docs/OPERATOR_CONFIG_AUDIT.md` §6.8 for the full excluded list and the reasoning per group.
 *
 * SECRETS ARE STRUCTURALLY EXCLUDED
 *
 * `assertNoSensitiveKeys()` below cross-checks every `envVar` against `EXPLICIT_ENV_CLASS` in
 * `src/env/secrets.ts` — the taxonomy the codebase already uses — and throws if a `secret` or
 * `identity` variable is ever registered. A test calls it, so the guard cannot rot into a comment.
 *
 * DEFAULTS MIRROR `loadBoxConfig()` EXACTLY
 *
 * Every `codeDefault` here is the same literal `src/box/config.ts` uses. They are kept honest by
 * `tests/operatorConfig/registryParity.test.mjs`, which reads the loader's source and compares, so a
 * future change to one side cannot silently drift from the other. That parity is what makes "first
 * deployment behaves exactly as before" true rather than hoped for.
 */

import type { SettingSpec, SettingValue } from "./types.js";

/** Bounds shared with the legacy `BOX_TUNING_LIMITS`, so the two entry points cannot disagree. */
const RUPEE_MAX = 1_000_000;

/**
 * Every runtime-configurable setting, grouped by the screen it appears on.
 *
 * Ordering within a category is the display order.
 */
export const OPERATOR_SETTINGS: readonly SettingSpec[] = [
  /* ══════════════════════════ STRATEGY ══════════════════════════ */
  {
    key: "minExpectedNetProfit",
    envVar: "BOX_MIN_EXPECTED_NET_PROFIT",
    boxConfigField: "minExpectedNetProfit",
    category: "strategy",
    label: "Minimum expected net profit",
    description:
      "The entry gate. A Box must show at least this much expected profit after every charge, slippage estimate and the safety buffer before it is entered.",
    type: "number",
    unit: "rupees",
    min: 0,
    max: RUPEE_MAX,
    // `replace`, not `floor`, for backward compatibility: this knob is ALREADY database-authoritative
    // through box_settings, and existing deployments may have deliberately persisted a value below
    // their env figure. Turning that into max(env, runtime) would change their behaviour on upgrade.
    // Documented as a conscious exception in the audit rather than smoothed over.
    containment: "replace",
    safeDirection: "higher_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "safetyBuffer",
    envVar: "BOX_SAFETY_BUFFER",
    boxConfigField: "safetyBuffer",
    category: "strategy",
    label: "Safety buffer",
    description:
      "Risk allowance deducted inside the expected-net figure, so a Box must clear its threshold with room to spare.",
    type: "number",
    unit: "rupees",
    min: 0,
    max: RUPEE_MAX,
    containment: "replace",
    safeDirection: "higher_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "minGrossEdge",
    envVar: "MIN_BOX_GROSS_EDGE",
    boxConfigField: "minGrossEdge",
    category: "strategy",
    label: "Prefilter gross edge",
    description:
      "A cheap first filter: the raw mispricing a candidate must show before the full costed qualification runs. Always held at or below the real net gate, so it cannot discard a Box that would have qualified.",
    type: "number",
    unit: "rupees",
    min: 0,
    max: RUPEE_MAX,
    containment: "replace",
    safeDirection: "higher_is_safer",
    policy: "HOT_SAFE",
    takesEffect: "next_candidate",
    dangerous: false,
    requiresFullAdmin: false,
  },
  {
    key: "expectedEntrySlippage",
    envVar: "BOX_EXPECTED_ENTRY_SLIPPAGE",
    boxConfigField: "expectedEntrySlippage",
    category: "strategy",
    label: "Expected entry slippage",
    description:
      "Assumed entry slippage, subtracted when judging expected profit. Lowering it makes every candidate look more profitable than it is.",
    type: "number",
    unit: "rupees",
    min: 0,
    max: RUPEE_MAX,
    containment: "replace",
    safeDirection: "higher_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "expectedExitSlippage",
    envVar: "BOX_EXPECTED_EXIT_SLIPPAGE",
    boxConfigField: "expectedExitSlippage",
    category: "strategy",
    label: "Expected exit slippage",
    description:
      "Assumed exit slippage, subtracted when judging expected profit and the realisable exit figure.",
    type: "number",
    unit: "rupees",
    min: 0,
    max: RUPEE_MAX,
    containment: "replace",
    safeDirection: "higher_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
  },

  /*
   * ── THE SAME FIVE ECONOMICS, EXPRESSED PER UNIT OF QUANTITY ──────────────────────────────────
   *
   * A Box's gross edge is `grossEdgePerUnit x lotSize`, so it scales with the lot. The flat rupee
   * figures above do not. Because F&O lots span ~35 to 40,000+, one flat figure is a ~1000x
   * different per-unit hurdle depending on the instrument — which is not one policy applied to the
   * universe, it is "never trade the small lots, take almost anything on the large ones".
   *
   * Each rate below resolves against a candidate's own lot as `max(flat, rate x lotSize)`. Every
   * one defaults to 0, which reproduces the flat arithmetic exactly.
   *
   * `zeroMeans: "value"` is the correct declaration, NOT `"disabled"`. Although 0 does switch the
   * rate off, `"disabled"` in this registry is the AMBIGUOUS-SENTINEL meaning reserved for ceilings
   * where 0 removes a bound — `toComparable` maps it to +Infinity, i.e. maximally permissive. These
   * are `higher_is_safer` requirements, so 0 is genuinely the numerically LOWEST and least safe
   * setting, exactly what `"value"` expresses. Declaring `"disabled"` would invert their comparison
   * and tell the policy layer that lowering a rate to 0 was a tightening.
   */
  {
    key: "minExpectedNetProfitPerUnit",
    envVar: "BOX_MIN_EXPECTED_NET_PROFIT_PER_UNIT",
    boxConfigField: "minExpectedNetProfitPerUnit",
    category: "strategy",
    label: "Minimum expected net profit per unit",
    description:
      "The entry gate expressed per unit of quantity, so one setting means the same hurdle on a 35-lot index and a 40,000-lot stock. A candidate must clear whichever is higher: the flat gate, or this rate times its lot size. 0 leaves the flat gate acting alone.",
    type: "number",
    unit: "rupees",
    min: 0,
    max: RUPEE_MAX,
    zeroMeans: "value",
    containment: "replace",
    safeDirection: "higher_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "minGrossEdgePerUnit",
    envVar: "MIN_BOX_GROSS_EDGE_PER_UNIT",
    boxConfigField: "minGrossEdgePerUnit",
    category: "strategy",
    label: "Prefilter gross edge per unit",
    description:
      "The cheap first filter expressed per unit of quantity. Held at or below the per-unit net gate at startup, because above it the prefilter would discard candidates that would have qualified. 0 leaves the flat prefilter acting alone.",
    type: "number",
    unit: "rupees",
    min: 0,
    max: RUPEE_MAX,
    zeroMeans: "value",
    containment: "replace",
    safeDirection: "higher_is_safer",
    policy: "HOT_SAFE",
    takesEffect: "next_candidate",
    dangerous: false,
    requiresFullAdmin: false,
  },
  {
    key: "safetyBufferPerUnit",
    envVar: "BOX_SAFETY_BUFFER_PER_UNIT",
    boxConfigField: "safetyBufferPerUnit",
    category: "strategy",
    label: "Safety buffer per unit",
    description:
      "The risk allowance expressed per unit of quantity, deducted inside the expected-net figure. A candidate is charged whichever is higher: the flat buffer, or this rate times its lot size.",
    type: "number",
    unit: "rupees",
    min: 0,
    max: RUPEE_MAX,
    zeroMeans: "value",
    containment: "replace",
    safeDirection: "higher_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "expectedEntrySlippagePerUnit",
    envVar: "BOX_EXPECTED_ENTRY_SLIPPAGE_PER_UNIT",
    boxConfigField: "expectedEntrySlippagePerUnit",
    category: "strategy",
    label: "Expected entry slippage per unit",
    description:
      "Assumed entry slippage per unit of quantity. This is the figure a flat rupee amount got most wrong, because slippage is ticks times quantity: a flat allowance understates the true cost on a large lot by almost all of it, making exactly those candidates look more profitable than they are.",
    type: "number",
    unit: "rupees",
    min: 0,
    max: RUPEE_MAX,
    zeroMeans: "value",
    containment: "replace",
    safeDirection: "higher_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "expectedExitSlippagePerUnit",
    envVar: "BOX_EXPECTED_EXIT_SLIPPAGE_PER_UNIT",
    boxConfigField: "expectedExitSlippagePerUnit",
    category: "strategy",
    label: "Expected exit slippage per unit",
    description:
      "Assumed exit slippage per unit of quantity, used when judging expected profit at entry and the realisable exit figure while a position is open. Same reasoning as the entry rate.",
    type: "number",
    unit: "rupees",
    min: 0,
    max: RUPEE_MAX,
    zeroMeans: "value",
    containment: "replace",
    safeDirection: "higher_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "strikeLevel",
    envVar: "BOX_STRIKE_LEVEL",
    boxConfigField: "defaultStrikeLevel",
    category: "strategy",
    label: "Strike width from ATM",
    description:
      "How far either side of at-the-money the Box legs are chosen. Changing this changes which contracts are subscribed, so it is not applied mid-session.",
    type: "integer",
    unit: "count",
    min: 1,
    max: 3,
    containment: "replace",
    safeDirection: "neutral",
    policy: "FLAT_AND_DISARMED",
    takesEffect: "immediately",
    dangerous: false,
    requiresFullAdmin: true,
  },
  {
    key: "enableShortBox",
    envVar: "BOX_ENABLE_SHORT_BOX",
    boxConfigField: "enableShortBox",
    category: "strategy",
    label: "Allow short Box entries",
    description:
      "Permits the short direction as well as the long. Enabling this admits a whole additional class of position.",
    type: "boolean",
    unit: "none",
    containment: "ceiling",
    safeDirection: "disabled_is_safer",
    policy: "FLAT_AND_DISARMED",
    takesEffect: "immediately",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "convergenceFloor",
    envVar: "BOX_CONVERGENCE_FLOOR",
    boxConfigField: "convergenceFloor",
    category: "strategy",
    label: "Convergence floor",
    description: "How close to fully converged a Box must be before the convergence exit rule fires.",
    type: "number",
    unit: "rupees",
    min: 0,
    max: RUPEE_MAX,
    containment: "replace",
    safeDirection: "neutral",
    policy: "HOT_SAFE",
    takesEffect: "next_candidate",
    dangerous: false,
    requiresFullAdmin: false,
  },
  {
    key: "convergencePct",
    envVar: "BOX_CONVERGENCE_PCT",
    boxConfigField: "convergencePct",
    category: "strategy",
    label: "Convergence fraction",
    description:
      "The convergence threshold as a fraction of the edge recorded at entry, used alongside the floor.",
    type: "number",
    unit: "ratio",
    min: 0,
    max: 1,
    containment: "replace",
    safeDirection: "neutral",
    policy: "HOT_SAFE",
    takesEffect: "next_candidate",
    dangerous: false,
    requiresFullAdmin: false,
  },
  {
    key: "minExitNetPnl",
    envVar: "BOX_MIN_EXIT_NET_PNL",
    boxConfigField: "minExitNetPnl",
    category: "strategy",
    label: "Minimum profit to take",
    description:
      "How much an exit must net before the engine takes profit voluntarily. This is a profit target, NOT an exit permission — expiry-safety exits, manual closes, protective cancels and emergency flattening ignore it entirely.",
    type: "number",
    unit: "rupees",
    min: 0,
    max: RUPEE_MAX,
    containment: "replace",
    safeDirection: "neutral",
    policy: "HOT_SAFE",
    takesEffect: "next_candidate",
    dangerous: false,
    requiresFullAdmin: false,
    caveat:
      "Raising this delays an automatic take-profit. It can never prevent risk reduction: EXPIRY_SAFETY overrides profitability, and no protective or emergency path consults this value.",
  },
  {
    key: "minExitNetPnlPerUnit",
    envVar: "BOX_MIN_EXIT_NET_PNL_PER_UNIT",
    boxConfigField: "minExitNetPnlPerUnit",
    category: "strategy",
    label: "Minimum profit to take per unit",
    description:
      "The voluntary take-profit target expressed per unit of quantity, so it scales with the lot exactly as the entry gate does. Set alongside the per-unit entry gate: if entry demands a lot-relative profit while this stays flat, a large-lot Box is entered against a real hurdle and then released against a trivial one. 0 leaves the flat target acting alone.",
    type: "number",
    unit: "rupees",
    min: 0,
    max: RUPEE_MAX,
    zeroMeans: "value",
    containment: "replace",
    safeDirection: "neutral",
    policy: "HOT_SAFE",
    takesEffect: "next_candidate",
    dangerous: false,
    requiresFullAdmin: false,
    caveat:
      "Like the flat target, this is a profit goal and never an exit permission. EXPIRY_SAFETY, manual closes, protective cancels and emergency flattening all ignore it.",
  },
  {
    key: "profitCapturePct",
    envVar: "BOX_PROFIT_CAPTURE_PCT",
    boxConfigField: "profitCapturePct",
    category: "strategy",
    label: "Profit capture target",
    description: "The fraction of the entry edge at which the profit-capture exit rule fires.",
    type: "number",
    unit: "ratio",
    min: 0,
    max: 1,
    containment: "replace",
    safeDirection: "neutral",
    policy: "HOT_SAFE",
    takesEffect: "next_candidate",
    dangerous: false,
    requiresFullAdmin: false,
  },
  {
    key: "minCapturedPct",
    envVar: "BOX_MIN_CAPTURED_PCT",
    boxConfigField: "minCapturedPct",
    category: "strategy",
    label: "Minimum captured fraction",
    description: "The alternative capture test: how much of the original edge has been realised.",
    type: "number",
    unit: "ratio",
    min: 0,
    max: 1,
    containment: "replace",
    safeDirection: "neutral",
    policy: "HOT_SAFE",
    takesEffect: "next_candidate",
    dangerous: false,
    requiresFullAdmin: false,
  },
  {
    key: "expirySafetyMinutes",
    envVar: "BOX_EXPIRY_SAFETY_MINUTES",
    boxConfigField: "expirySafetyMinutesBeforeClose",
    category: "strategy",
    label: "Expiry safety margin",
    description:
      "How long before expiry-day close new entry stops. Lowering it permits entry closer to expiry.",
    type: "number",
    unit: "minutes",
    min: 0,
    max: 600,
    containment: "floor",
    safeDirection: "higher_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
  },

  /* ════════════════════════════ RISK ════════════════════════════ */
  {
    key: "maxOpenBoxes",
    envVar: "BOX_MAX_OPEN_BOXES",
    boxConfigField: "maxOpenBoxes",
    category: "risk",
    label: "Maximum Box inventory",
    description:
      "How many Boxes may be held at once, in total, in every execution mode. Zero means unlimited. Exits, reductions and protective cancels are never affected by this.",
    type: "integer",
    unit: "count",
    min: 0,
    max: 50,
    zeroMeans: "unlimited",
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "oneActiveBoxPerUnderlying",
    envVar: "BOX_ONE_ACTIVE_BOX_PER_UNDERLYING",
    boxConfigField: "oneActiveBoxPerUnderlying",
    category: "risk",
    label: "One active Box per underlying",
    description:
      "Prevents a second Box being opened on an underlying that already has exposure, a partial position or an unresolved residual leg.",
    type: "boolean",
    unit: "none",
    containment: "floor",
    safeDirection: "enabled_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "maxConcurrentPerUnderlying",
    envVar: "BOX_MAX_CONCURRENT_PER_UNDERLYING",
    boxConfigField: "maxConcurrentPerUnderlying",
    category: "risk",
    label: "Concurrent executions per underlying",
    description:
      "A budget on how many executions may be in flight on one underlying. Zero disables the budget.",
    type: "integer",
    unit: "count",
    min: 0,
    max: 16,
    zeroMeans: "unlimited",
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: false,
    requiresFullAdmin: true,
  },
  {
    key: "liveMaxBoxCapitalRupees",
    envVar: "BOX_LIVE_MAX_BOX_CAPITAL_RUPEES",
    boxConfigField: "liveMaxBoxCapitalRupees",
    category: "risk",
    label: "Maximum capital per Box (live)",
    description:
      "The largest gross entry-order notional a single live Box may commit. Zero disables the cap. Applies to entry only — an exit, protective cancel or emergency flatten is never refused by it.",
    type: "integer",
    unit: "rupees",
    min: 0,
    max: 1_000_000_000,
    zeroMeans: "unlimited",
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    // FLAT_AND_DISARMED rather than TIGHTEN_ONLY, and the reason is specific: this limit is read
    // LIVE at admission (executionGateway.capitalLimitRupees) but from a CONSTRUCTION-TIME COPY at
    // the order manager's dequeue re-check (orderManagerLimitsFromConfig). Raising it while armed
    // would let admission accept a Box that the send boundary then refuses against the stale copy —
    // and by then a session entry attempt has already been spent. See audit §3.3.
    policy: "FLAT_AND_DISARMED",
    takesEffect: "immediately",
    dangerous: true,
    requiresFullAdmin: true,
    liveOnly: true,
    caveat:
      "Enforced twice: once at admission and once at the send boundary, where the value is captured when the live order manager is built. It is therefore only changed while flat and disarmed.",
  },
  {
    key: "paperMaxBoxCapitalRupees",
    envVar: "BOX_PAPER_MAX_BOX_CAPITAL_RUPEES",
    boxConfigField: "paperMaxBoxCapitalRupees",
    category: "risk",
    label: "Maximum capital per Box (paper)",
    description: "The same cap for paper execution. Zero disables it.",
    type: "integer",
    unit: "rupees",
    min: 0,
    max: 1_000_000_000,
    zeroMeans: "unlimited",
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "HOT_SAFE",
    takesEffect: "next_candidate",
    dangerous: false,
    requiresFullAdmin: false,
    paperOnly: true,
  },
  {
    key: "liveMaxOpenBoxes",
    envVar: "BOX_LIVE_MAX_OPEN_BOXES",
    boxConfigField: "liveMaxOpenBoxes",
    category: "risk",
    label: "Live open-Box limit",
    description:
      "The live order manager's own open-Box ceiling, checked at order admission. Distinct from the inventory ceiling, which is enforced earlier and in every mode. Zero blocks all new entry.",
    type: "integer",
    unit: "count",
    min: 0,
    max: 20,
    // NOT `unlimited`: the manager tests `openBoxes >= limit`, so 0 refuses every entry. Zero here is
    // the MOST restrictive value, not the least.
    zeroMeans: "value",
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "FLAT_AND_DISARMED",
    takesEffect: "immediately",
    dangerous: true,
    requiresFullAdmin: true,
    liveOnly: true,
  },
  {
    key: "liveDailyLossLimit",
    envVar: "BOX_LIVE_DAILY_LOSS_LIMIT",
    boxConfigField: "liveDailyLossLimit",
    category: "risk",
    label: "Daily loss limit",
    description:
      "Realised loss for the day at which the live circuit breaker trips and new entry stops. Zero disables the limit.",
    type: "integer",
    unit: "rupees",
    min: 0,
    max: 10_000_000,
    zeroMeans: "unlimited",
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "FLAT_AND_DISARMED",
    takesEffect: "immediately",
    dangerous: true,
    requiresFullAdmin: true,
    liveOnly: true,
  },
  {
    key: "liveMaxResidualLegs",
    envVar: "BOX_LIVE_MAX_RESIDUAL_LEGS",
    boxConfigField: "liveMaxResidualLegs",
    category: "risk",
    label: "Residual leg tolerance",
    description:
      "How many unresolved residual legs may exist before new entry waits for them to clear. Zero means any residual leg stops entry.",
    type: "integer",
    unit: "count",
    min: 0,
    max: 4,
    zeroMeans: "value",
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "FLAT_AND_DISARMED",
    takesEffect: "immediately",
    dangerous: true,
    requiresFullAdmin: true,
    liveOnly: true,
  },
  {
    key: "liveMaxOpenLegQuantity",
    envVar: "BOX_LIVE_MAX_OPEN_LEG_QUANTITY",
    boxConfigField: "liveMaxOpenLegQuantity",
    category: "risk",
    label: "Maximum quantity per leg",
    description: "The largest quantity any single live leg may carry.",
    type: "integer",
    unit: "count",
    min: 1,
    max: 1_000_000,
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "FLAT_AND_DISARMED",
    takesEffect: "immediately",
    dangerous: true,
    requiresFullAdmin: true,
    liveOnly: true,
    caveat:
      "Checked both in the coordinator's entry prologue and at the send boundary, where it is captured at order-manager construction. Changed only while flat and disarmed.",
  },
  {
    key: "liveMaxGrossOpenLegQuantity",
    envVar: "BOX_LIVE_MAX_GROSS_OPEN_LEG_QUANTITY",
    boxConfigField: "liveMaxGrossOpenLegQuantity",
    category: "risk",
    label: "Maximum gross quantity",
    description: "The largest total quantity across all four legs of a live Box.",
    type: "integer",
    unit: "count",
    min: 1,
    max: 4_000_000,
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "FLAT_AND_DISARMED",
    takesEffect: "immediately",
    dangerous: true,
    requiresFullAdmin: true,
    liveOnly: true,
  },
  {
    key: "liveMaxConcurrentExecutions",
    envVar: "BOX_LIVE_MAX_CONCURRENT_EXECUTIONS",
    boxConfigField: "liveMaxConcurrentExecutions",
    category: "risk",
    label: "Live execution concurrency",
    description: "How many live Box executions may run at once.",
    type: "integer",
    unit: "count",
    min: 1,
    max: 4,
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "FLAT_AND_DISARMED",
    takesEffect: "immediately",
    dangerous: true,
    requiresFullAdmin: true,
    liveOnly: true,
  },
  {
    key: "liveRequireFundsCover",
    envVar: "BOX_LIVE_REQUIRE_FUNDS_COVER",
    boxConfigField: "liveRequireFundsCover",
    category: "risk",
    label: "Require funds cover",
    description:
      "Blocks live entry unless fresh broker funds evidence proves the account can cover it. Turning this off removes that proof requirement.",
    type: "boolean",
    unit: "none",
    containment: "floor",
    safeDirection: "enabled_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
    liveOnly: true,
  },
  {
    key: "liveRequireMarginEvidence",
    envVar: "BOX_LIVE_REQUIRE_MARGIN_EVIDENCE",
    boxConfigField: "liveRequireMarginEvidence",
    category: "risk",
    label: "Require margin evidence",
    description:
      "Blocks live entry unless fresh broker margin evidence is available for the Box being entered.",
    type: "boolean",
    unit: "none",
    containment: "floor",
    safeDirection: "enabled_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
    liveOnly: true,
  },
  {
    key: "liveRecoveryReserveRupees",
    envVar: "BOX_LIVE_RECOVERY_RESERVE_RUPEES",
    boxConfigField: "liveRecoveryReserveRupees",
    category: "risk",
    label: "Recovery reserve",
    description:
      "Funds held back from entry so an unwind or recovery always has headroom. Zero disables the reserve.",
    type: "integer",
    unit: "rupees",
    min: 0,
    max: 100_000_000,
    containment: "floor",
    safeDirection: "higher_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
    liveOnly: true,
  },
  {
    key: "sessionMaxCompletedTrades",
    envVar: "BOX_SESSION_MAX_COMPLETED_TRADES",
    boxConfigField: "sessionMaxCompletedTrades",
    category: "risk",
    label: "Session completed-trade ceiling",
    description:
      "How many Box cycles one armed session may consume. Zero means unlimited. The armed session keeps the value it was armed under; a change here applies to the NEXT arm.",
    type: "integer",
    unit: "count",
    min: 0,
    max: 10_000,
    zeroMeans: "unlimited",
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    // NEXT_SESSION is the whole point: tradingSession.armSession() snapshots this at ARM, and a
    // config change must never retroactively widen a session already armed.
    policy: "NEXT_SESSION",
    takesEffect: "next_arm",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "sessionMaxEntryAttempts",
    envVar: "BOX_SESSION_MAX_ENTRY_ATTEMPTS",
    boxConfigField: "sessionMaxEntryAttempts",
    category: "risk",
    label: "Session entry-attempt ceiling",
    description:
      "How many entry attempts one armed session may start, including attempts that took exposure and were unwound. Zero means unlimited. Applies to the NEXT arm.",
    type: "integer",
    unit: "count",
    min: 0,
    max: 10_000,
    zeroMeans: "unlimited",
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "NEXT_SESSION",
    takesEffect: "next_arm",
    dangerous: true,
    requiresFullAdmin: true,
  },

  /* ═════════════════════════ MARKET DATA ═════════════════════════ */
  {
    key: "quoteMaxAgeMs",
    envVar: "BOX_QUOTE_MAX_AGE_MS",
    boxConfigField: "quoteMaxAgeMs",
    category: "market_data",
    label: "Quote freshness limit",
    description: "How long an unchanged order book stays valid for pricing and admission.",
    type: "integer",
    unit: "milliseconds",
    min: 250,
    max: 120_000,
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "FLAT_AND_DISARMED",
    takesEffect: "immediately",
    dangerous: true,
    requiresFullAdmin: true,
    caveat:
      "Also captured by the market-data state machine when the engine is built, so entry admission and feed health must agree. Changed only while flat and disarmed.",
  },
  {
    key: "feedMaxAgeMs",
    envVar: "BOX_FEED_MAX_AGE_MS",
    boxConfigField: "feedMaxAgeMs",
    category: "market_data",
    label: "Feed heartbeat limit",
    description: "How long the market-data feed may go quiet before it is treated as unhealthy.",
    type: "integer",
    unit: "milliseconds",
    min: 250,
    max: 120_000,
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "FLAT_AND_DISARMED",
    takesEffect: "immediately",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "underlyingMaxAgeMs",
    envVar: "BOX_UNDERLYING_MAX_AGE_MS",
    boxConfigField: "underlyingMaxAgeMs",
    category: "market_data",
    label: "Underlying freshness limit",
    description: "How stale the underlying price may be while still admitting a candidate.",
    type: "integer",
    unit: "milliseconds",
    min: 250,
    max: 120_000,
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "maxCrossLegReceiveDispersionMs",
    envVar: "BOX_MAX_CROSS_LEG_RECEIVE_DISPERSION_MS",
    boxConfigField: "maxCrossLegReceiveDispersionMs",
    category: "market_data",
    label: "Cross-leg receive-time coherence",
    description:
      "How far apart the four legs' books may arrive at this server. This is the primary live coherence gate: it is measured on our own millisecond clock, which is always present.",
    type: "integer",
    unit: "milliseconds",
    min: 0,
    max: 60_000,
    zeroMeans: "disabled",
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "maxCrossLegExchangeDispersionMs",
    envVar: "BOX_MAX_CROSS_LEG_EXCHANGE_DISPERSION_MS",
    boxConfigField: "maxCrossLegExchangeDispersionMs",
    category: "market_data",
    label: "Cross-leg exchange-time coherence",
    description:
      "How far apart the four legs' exchange timestamps may be. A coarse sanity check, not the precise gate.",
    type: "integer",
    unit: "milliseconds",
    min: 0,
    max: 60_000,
    zeroMeans: "disabled",
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
    caveat:
      "Zerodha's book timestamp is in whole seconds, so measured dispersion can only ever be 0 ms, 1000 ms, 2000 ms and so on. Any value below about 1000 ms is unsatisfiable by quantisation alone and will reject perfectly coherent books — a 250 ms setting once produced 100% refusals on a healthy feed. Sub-second coherence is enforced by the receive-time limit instead.",
  },
  {
    key: "maxReceiveToExchangeDelayMs",
    envVar: "BOX_MAX_RECEIVE_TO_EXCHANGE_DELAY_MS",
    boxConfigField: "maxReceiveToExchangeDelayMs",
    category: "market_data",
    label: "Feed delay tolerance",
    description:
      "How long after the exchange published a book it may still arrive here. Tolerates coarse exchange stamps and normal feed latency.",
    type: "integer",
    unit: "milliseconds",
    min: 0,
    max: 120_000,
    zeroMeans: "disabled",
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "coherenceZeroDispersionDisablesInLive",
    envVar: "BOX_COHERENCE_ZERO_DISPERSION_DISABLES_IN_LIVE",
    boxConfigField: "coherenceZeroDispersionDisablesInLive",
    category: "market_data",
    label: "Treat a zero coherence limit as disabled in live",
    description:
      "By default a zero dispersion limit is impossible to satisfy in live, which fails safe. Enabling this reinterprets zero as 'coherence checking off'.",
    type: "boolean",
    unit: "none",
    containment: "ceiling",
    safeDirection: "disabled_is_safer",
    policy: "FLAT_AND_DISARMED",
    takesEffect: "immediately",
    dangerous: true,
    requiresFullAdmin: true,
  },

  /* ═══════════════════════ PAPER / CALIBRATION ═══════════════════════ */
  {
    key: "paperExecutionProfile",
    envVar: "BOX_PAPER_EXECUTION_PROFILE",
    boxConfigField: "paperExecutionProfile",
    category: "paper",
    label: "Paper execution profile",
    description:
      "How faithfully paper execution models the live path. 'live_parity' uses recorded latency; 'stress' injects synthetic faults and can never be combined with live execution.",
    type: "enum",
    unit: "none",
    enumValues: ["standard", "live_parity", "stress"],
    forbiddenValuesInLive: ["stress"],
    containment: "replace",
    safeDirection: "neutral",
    policy: "FLAT_AND_DISARMED",
    takesEffect: "immediately",
    dangerous: false,
    requiresFullAdmin: true,
    paperOnly: true,
  },
  {
    key: "simulatedLatencyMs",
    envVar: "BOX_SIMULATED_LATENCY_MS",
    boxConfigField: "simulatedLatencyMs",
    category: "paper",
    label: "Simulated latency",
    description: "Modelled delay from decision to exchange arrival in paper execution.",
    type: "integer",
    unit: "milliseconds",
    min: 0,
    max: 60_000,
    containment: "replace",
    safeDirection: "neutral",
    policy: "HOT_SAFE",
    takesEffect: "next_candidate",
    dangerous: false,
    requiresFullAdmin: false,
    paperOnly: true,
  },
  {
    key: "simulatedDecisionMs",
    envVar: "BOX_SIMULATED_DECISION_MS",
    boxConfigField: "simulatedDecisionMs",
    category: "paper",
    label: "Simulated decision time",
    description: "Modelled time spent deciding, before latency is applied.",
    type: "integer",
    unit: "milliseconds",
    min: 0,
    max: 60_000,
    containment: "replace",
    safeDirection: "neutral",
    policy: "HOT_SAFE",
    takesEffect: "next_candidate",
    dangerous: false,
    requiresFullAdmin: false,
    paperOnly: true,
  },
  {
    key: "paperMaxConcurrentExecutions",
    envVar: "BOX_PAPER_MAX_CONCURRENT_EXECUTIONS",
    boxConfigField: "paperMaxConcurrentExecutions",
    category: "paper",
    label: "Paper execution concurrency",
    description:
      "How many paper executions may run at once. Defaults to the live cap so a rehearsal matches a conservative live deployment.",
    type: "integer",
    unit: "count",
    min: 1,
    max: 8,
    containment: "replace",
    safeDirection: "lower_is_safer",
    policy: "HOT_SAFE",
    takesEffect: "next_candidate",
    dangerous: false,
    requiresFullAdmin: false,
    paperOnly: true,
  },

  /* ═══════════════════════════ UNIVERSE ═══════════════════════════ */
  {
    key: "maxUnderlyings",
    envVar: "BOX_MAX_UNDERLYINGS",
    boxConfigField: "maxUnderlyings",
    category: "universe",
    label: "Maximum underlyings watched",
    description:
      "How many underlyings the scanner may watch. Zero means no limit. Raising it increases the broker rate-limit pressure the whole strategy depends on.",
    type: "integer",
    unit: "count",
    min: 0,
    max: 1_000,
    zeroMeans: "unlimited",
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "immediately",
    dangerous: false,
    requiresFullAdmin: true,
  },
  {
    key: "maxSubscribedTokens",
    envVar: "BOX_MAX_SUBSCRIBED_TOKENS",
    boxConfigField: "maxSubscribedTokens",
    category: "universe",
    label: "Maximum subscribed instruments",
    description: "A ceiling on how many instrument tokens the market-data lane may subscribe to.",
    type: "integer",
    unit: "count",
    min: 1,
    max: 10_000,
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "immediately",
    dangerous: false,
    requiresFullAdmin: true,
  },
  {
    key: "indicativeDiscovery",
    envVar: "BOX_INDICATIVE_DISCOVERY",
    boxConfigField: "indicativeDiscovery",
    category: "universe",
    label: "Closed-market indicative discovery",
    description:
      "Polls indicative prices while the market is closed so the board is populated before the open.",
    type: "boolean",
    unit: "none",
    containment: "replace",
    safeDirection: "neutral",
    policy: "HOT_SAFE",
    takesEffect: "immediately",
    dangerous: false,
    requiresFullAdmin: false,
  },
  {
    key: "indicativeMaxUnderlyings",
    envVar: "BOX_INDICATIVE_MAX_UNDERLYINGS",
    boxConfigField: "indicativeMaxUnderlyings",
    category: "universe",
    label: "Indicative discovery breadth",
    description: "How many underlyings the closed-market indicative pass covers.",
    type: "integer",
    unit: "count",
    min: 1,
    max: 1_000,
    containment: "ceiling",
    safeDirection: "lower_is_safer",
    policy: "HOT_SAFE",
    takesEffect: "immediately",
    dangerous: false,
    requiresFullAdmin: false,
  },
  {
    key: "maxPublishedOpportunities",
    envVar: "BOX_MAX_PUBLISHED_OPPORTUNITIES",
    boxConfigField: "maxPublishedOpportunities",
    category: "universe",
    label: "Opportunities published",
    description: "How many ranked opportunities the board sends to the UI. Presentation only.",
    type: "integer",
    unit: "count",
    min: 1,
    max: 500,
    containment: "replace",
    safeDirection: "neutral",
    policy: "HOT_SAFE",
    takesEffect: "immediately",
    dangerous: false,
    requiresFullAdmin: false,
  },
  {
    key: "windowMinIntervalMs",
    envVar: "BOX_WINDOW_MIN_INTERVAL_MS",
    boxConfigField: "windowMinIntervalMs",
    category: "universe",
    label: "Strike window hold time",
    description: "The shortest time between strike-window rebuilds, which damps churn around ATM.",
    type: "integer",
    unit: "milliseconds",
    min: 0,
    max: 600_000,
    containment: "replace",
    safeDirection: "neutral",
    policy: "HOT_SAFE",
    takesEffect: "immediately",
    dangerous: false,
    requiresFullAdmin: false,
  },

  /* ════════════════════════════ CHARGES ════════════════════════════ */
  {
    key: "requirePricedCharges",
    envVar: "BOX_REQUIRE_PRICED_CHARGES",
    boxConfigField: "requirePricedCharges",
    category: "charges",
    label: "Require priced charges",
    description:
      "Refuses entry unless every charge component has been priced. Turning this off admits Boxes whose true cost is estimated.",
    type: "boolean",
    unit: "none",
    containment: "floor",
    safeDirection: "enabled_is_safer",
    policy: "TIGHTEN_ONLY_WHILE_ARMED",
    takesEffect: "next_candidate",
    dangerous: true,
    requiresFullAdmin: true,
  },
  {
    key: "prefilterChargeAllowance",
    envVar: "BOX_PREFILTER_CHARGE_ALLOWANCE",
    boxConfigField: "prefilterChargeAllowance",
    category: "charges",
    label: "Prefilter charge allowance",
    description: "The charge figure assumed by the cheap prefilter before real charges are priced.",
    type: "number",
    unit: "rupees",
    min: 0,
    max: RUPEE_MAX,
    containment: "replace",
    safeDirection: "higher_is_safer",
    policy: "HOT_SAFE",
    takesEffect: "next_candidate",
    dangerous: false,
    requiresFullAdmin: false,
  },
  {
    key: "reconcileCharges",
    envVar: "BOX_RECONCILE_CHARGES",
    boxConfigField: "reconcileCharges",
    category: "charges",
    label: "Reconcile charges against the broker",
    description: "Re-reads actual charges from the broker after a trade and records any divergence.",
    type: "boolean",
    unit: "none",
    containment: "replace",
    safeDirection: "enabled_is_safer",
    policy: "HOT_SAFE",
    takesEffect: "immediately",
    dangerous: false,
    requiresFullAdmin: false,
  },
  {
    key: "chargeReconcileWarnPct",
    envVar: "BOX_CHARGE_RECONCILE_WARN_PCT",
    boxConfigField: "chargeReconcileWarnPct",
    category: "charges",
    label: "Charge divergence warning threshold",
    description: "How far modelled charges may differ from the broker's before a warning is raised.",
    type: "number",
    unit: "percent",
    min: 0,
    max: 100,
    containment: "replace",
    safeDirection: "lower_is_safer",
    policy: "HOT_SAFE",
    takesEffect: "immediately",
    dangerous: false,
    requiresFullAdmin: false,
  },
];

/**
 * The code defaults, kept in a separate map from the specs.
 *
 * Separate because a spec describes the SHAPE of a setting (bounds, policy, units) while the default
 * is a VALUE that must track `loadBoxConfig()` literal-for-literal. Keeping them apart makes the
 * parity test a straightforward comparison against the loader's source rather than a walk over
 * heterogeneous objects.
 */
export const CODE_DEFAULTS: ReadonlyMap<string, SettingValue> = new Map<string, SettingValue>([
  // strategy
  ["minExpectedNetProfit", 1200],
  ["safetyBuffer", 150],
  ["minGrossEdge", 1200],
  ["expectedEntrySlippage", 250],
  ["expectedExitSlippage", 250],
  // The per-unit rates. All 0 so a first deployment reproduces the flat arithmetic exactly; the
  // parity test matches each against the literal in `loadBoxConfig`.
  ["minExpectedNetProfitPerUnit", 0],
  ["minGrossEdgePerUnit", 0],
  ["safetyBufferPerUnit", 0],
  ["expectedEntrySlippagePerUnit", 0],
  ["expectedExitSlippagePerUnit", 0],
  ["minExitNetPnlPerUnit", 0],
  ["strikeLevel", 3],
  ["enableShortBox", true],
  ["convergenceFloor", 200],
  ["convergencePct", 0.2],
  ["minExitNetPnl", 600],
  ["profitCapturePct", 0.75],
  ["minCapturedPct", 0.75],
  ["expirySafetyMinutes", 45],
  // risk
  ["maxOpenBoxes", 0],
  ["oneActiveBoxPerUnderlying", false],
  ["maxConcurrentPerUnderlying", 2],
  ["liveMaxBoxCapitalRupees", 0],
  ["paperMaxBoxCapitalRupees", 0],
  ["liveMaxOpenBoxes", 1],
  ["liveDailyLossLimit", 5000],
  ["liveMaxResidualLegs", 1],
  ["liveMaxOpenLegQuantity", 100],
  ["liveMaxGrossOpenLegQuantity", 400],
  ["liveMaxConcurrentExecutions", 1],
  ["liveRequireFundsCover", false],
  ["liveRequireMarginEvidence", false],
  ["liveRecoveryReserveRupees", 0],
  ["sessionMaxCompletedTrades", 0],
  ["sessionMaxEntryAttempts", 0],
  // market data
  ["quoteMaxAgeMs", 15_000],
  ["feedMaxAgeMs", 5_000],
  ["underlyingMaxAgeMs", 10_000],
  ["maxCrossLegReceiveDispersionMs", 500],
  ["maxCrossLegExchangeDispersionMs", 1_000],
  ["maxReceiveToExchangeDelayMs", 5_000],
  ["coherenceZeroDispersionDisablesInLive", false],
  // paper
  ["paperExecutionProfile", "standard"],
  ["simulatedLatencyMs", 250],
  ["simulatedDecisionMs", 40],
  ["paperMaxConcurrentExecutions", 1],
  // universe
  ["maxUnderlyings", 0],
  ["maxSubscribedTokens", 2200],
  ["indicativeDiscovery", true],
  ["indicativeMaxUnderlyings", 150],
  ["maxPublishedOpportunities", 60],
  ["windowMinIntervalMs", 15_000],
  // charges
  ["requirePricedCharges", true],
  ["prefilterChargeAllowance", 160],
  ["reconcileCharges", true],
  ["chargeReconcileWarnPct", 5],
]);

/** Fast lookup by domain key. */
export const SETTINGS_BY_KEY: ReadonlyMap<string, SettingSpec> = new Map(
  OPERATOR_SETTINGS.map((spec) => [spec.key, spec] as const),
);

/** The persisted `box_settings.key` for a domain key. Stable, snake_case, decoupled from TS names. */
export function persistedKeyFor(key: string): string {
  return key.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`);
}

/**
 * THE SECURITY GUARD: no credential may ever become a runtime setting.
 *
 * Cross-checks every registered `envVar` against the codebase's existing classification in
 * `src/env/secrets.ts`. Takes the class lookup as a parameter rather than importing it, so this
 * module stays free of every dependency and can be exercised directly from source by the test
 * harness — the same property that makes it safe to assert on.
 *
 * Throws rather than returning a list: a secret reaching a configuration API is not a warning.
 */
export function assertNoSensitiveKeys(
  classOf: (envVar: string) => "secret" | "identity" | "config" | undefined,
): void {
  const offenders: string[] = [];
  for (const spec of OPERATOR_SETTINGS) {
    const cls = classOf(spec.envVar);
    if (cls === "secret" || cls === "identity") offenders.push(`${spec.key} (${spec.envVar}: ${cls})`);
  }
  if (offenders.length > 0) {
    throw new Error(
      `[operatorConfig] refusing to expose non-config environment variables through the runtime ` +
        `configuration API: ${offenders.join(", ")}`,
    );
  }
}

/** Every setting whose specification says it must never be writable. */
export function readOnlyKeys(): readonly string[] {
  return OPERATOR_SETTINGS.filter((s) => s.policy === "RESTART_REQUIRED").map((s) => s.key);
}
